---
title: "Herbicide_Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r}
# translate resistance_value to resistance_level
V2L <- function(resistance_value) {
    if (resistance_value >= 0.8) {
    resistance_level <- "#FF0000"} #Terrible
  else if (resistance_value >= 0.6) {
    resistance_level <- "#ff3300"} #Bad
  else if (resistance_value >= 0.4) {
    resistance_level <- "#ffcc00"} #Fair
  else if (resistance_value >= 0.2) {
    resistance_level <- "##ccff33"} #Good
  else {resistance_level <- "#66ff33"} #Excellent
  return(resistance_level)
  }

```

```{r}
Brent <- read_csv("C:\\Users\\ALEX\\Desktop\\test1\\separate_report\\csv\\Brent.csv")

for (resistance_value in Brent$Clethodim_SURVIVAL_RATE[]){
  print(V2L(resistance_value))
}
```

```{r}
Adam <- read_csv("C:\\Users\\ALEX\\Desktop\\test1\\csv\\Adam.csv")

resistance_level <- character()
# print(length(Adam$Clethodim_SURVIVAL_RATE[]))
for (resistance_value in Adam$Clethodim_SURVIVAL_RATE[]){
  if (resistance_value >= 0.8) {
  resistance_level <- "#FF0000"} #Terrible
else if (resistance_value >= 0.6) {
  resistance_level <- "#ff3300"} #Bad
else if (resistance_value >= 0.4) {
  resistance_level <- "#ffcc00"} #Fair
else if (resistance_value >= 0.2) {
  resistance_level <- "##ccff33"} #Good
else {resistance_level <- "#66ff33"} #Excellent
}

```

```{r}
# The loop was not successful
SURVIVAL_RATE <- c("Clethodim_SURVIVAL_RATE", "Glyphosate_SURVIVAL_RATE", "Sulfometuron_SURVIVAL_RATE", "Terbuthylazine_SURVIVAL_RATE")

for (sur in SURVIVAL_RATE){
  ggplot(Adam) +
  geom_bar(mapping = aes(x = Accession_Name, y = sur, fill = Farmer_Agronomist), stat = "identity") +
  scale_fill_manual(values = c("grey80", "grey65", "grey50", "grey35", as.character(resistance_level))) +
  theme(axis.text.x = element_text(size=7, angle=90))
  print(sur)
}
print("end")
```