---
title: "Herbicide Resistance"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Inputs, include=FALSE}
dat = read.delim("./test_data_Lrigidum_20200910.txt", header=TRUE, na.string="#N/A")

list_herbicides = c("Clethodim_SURVIVAL_RATE", "Glyphosate_SURVIVAL_RATE", "Sulfometuron_SURVIVAL_RATE", "Terbuthylazine_SURVIVAL_RATE")

list_farmer = unique(dat$Farmer_Agronomist)

list_subdat = list()
for (i in c(1:length(list_farmer))) {
  list_subdat[[i]] <- dat[dat$Farmer_Agronomist==list_farmer[i], ]
}
list_subdat <- setNames(list_subdat,list_farmer)
# print(list_subdat[["Adam"]])
```

```{r, OutputsDir, include=FALSE}
list_html_his = list()
for (i in c(1:length(list_farmer))) {
  list_html_his[i] <- paste0("./Plots/", list_farmer[i],".html")
  } #set the output directory
list_html_his <- setNames(list_html_his,list_farmer)
print(list_html_his)
```

```{r, Output, include=FALSE}
getwd()
for (name_farmer in list_farmer) {
  subdat = list_subdat[[name_farmer]]
  rmarkdown::render("./Plots.Rmd", output_file = list_html_his[[name_farmer]])
}
```
