---
title: "ToChris"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

```{r}
Chris <- read_csv("C:\\Users\\ALEX\\Desktop\\test1\\separate_report\\csv\\Chris.csv")

# Clethodim_SURVIVAL_RATE
ggplot(Chris) +
  geom_bar(mapping = aes(x = Accession_Name, y = Clethodim_SURVIVAL_RATE, fill = Farmer_Agronomist), stat = "identity") +
  scale_fill_manual(values = c("grey80", "grey65", "grey50", "grey35", "yellow")) +
  theme(axis.text.x = element_text(size=7, angle=90))

# Glyphosate_SURVIVAL_RATE
ggplot(Chris) +
  geom_bar(mapping = aes(x = Accession_Name, y = Glyphosate_SURVIVAL_RATE, fill = Farmer_Agronomist), stat = "identity") +
  scale_fill_manual(values = c("grey80", "grey65", "grey50", "grey35", "yellow")) +
  theme(axis.text.x = element_text(size=7, angle=90))

# Sulfometuron_SURVIVAL_RATE
ggplot(Chris) +
  geom_bar(mapping = aes(x = Accession_Name, y = Sulfometuron_SURVIVAL_RATE, fill = Farmer_Agronomist), stat = "identity") +
  scale_fill_manual(values = c("grey80", "grey65", "grey50", "grey35", "yellow")) +
  theme(axis.text.x = element_text(size=7, angle=90))

# Terbuthylazine_SURVIVAL_RATE
ggplot(Chris) +
  geom_bar(mapping = aes(x = Accession_Name, y = Terbuthylazine_SURVIVAL_RATE, fill = Farmer_Agronomist), stat = "identity") +
  scale_fill_manual(values = c("grey80", "grey65", "grey50", "grey35", "yellow")) +
  theme(axis.text.x = element_text(size=7, angle=90))
```