```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
list_herbicides = c("Clethodim", "Glyphosate", "Sulfometuron", "Terbuthylazine")
```

```{r 2}
x <- runif(10)
y <- runif(10)
color_gradient = rev(colorRampPalette(c("#A50026","#D73027","#F46D43","#FDAE61","#FEE08B","#FFFFBF","#D9EF8B","#A6D96A","#66BD63","#1A9850","#006837"))(ncolors))
xhist <- hist(x, breaks = 5, plot = FALSE)
yhist <- hist(y, breaks = 5, plot = FALSE)
top <- max(c(xhist$counts, yhist$counts))
print(xhist)
xrange <- c(0, 1)
yrange <- c(0, 1)
nf <- layout(matrix(c(2,0,1,3),2,2,byrow = TRUE), c(3,1), c(1,3), TRUE)
layout.show(nf)

par(mar = c(3,3,1,1))
plot(x, y, xlim = xrange, ylim = yrange, xlab = "", ylab = "", col=color_gradient)
par(mar = c(0,3,1,1))
barplot(xhist$counts, axes = FALSE, ylim = c(0, top), space = 0)
par(mar = c(3,0,1,1))
barplot(yhist$counts, axes = FALSE, xlim = c(0, top), space = 0, horiz = TRUE)

par(def.par)  #- reset to default
# }
```

```{r}
x = c(1,4,3)
print(range(x))
```



