---
title: "Demo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(maps)
getwd()
```

### Inputs:
```{r}
fname_data = "./data/POP_PHENO_DATA.txt"
name_farmer = "Farmer D"
dat = read.delim(fname_data, header=TRUE, na.string="#N/A")
subdat = dat[dat$Farmer_Agronomist==name_farmer, ]
list_herbicides = c("Clethodim")
```


```{r, Maps}
for (name_herbicide in list_herbicides){
  ## Load resistance data of each name_herbicide
  resistance = eval(parse(text=paste0("dat$", name_herbicide)))
  resistance = resistance[!is.na(resistance)] ## remove NA
  
  ## Load sub data (of each farmer, of each name_herbicide)
  subdat_resistance = eval(parse(text=paste0("subdat$", name_herbicide))) # "subdat_resistance" should be a numeric vector
  
  ## Open a new PNG device
  png(filename=paste0("./Image/", name_farmer, "/hist_", name_herbicide, ".png"))
  
  if (sum(!is.na(subdat_resistance))==0){
    ### if all data in this sub-dataset is NA, print "NO DATA"
    par(xpd=T)
    plot(x=0:1, y=0:1, type="n", xlab=name_herbicide, ylab="",)
    text(x=0.5, y=0.5, lab="NO DATA")
  } else {
    ### histogram
    par(xpd=T)
    h = hist(resistance, plot = F) # Obtain data in Histogram
    ymax = max(h$counts)
    hist(resistance, col=rgb(0.5,0.5,0.5,alpha=0.6), labels = TRUE, freq=T, breaks=10, bord=FALSE, main="", xlim = c(0,1), xlab=name_herbicide, ylim = c(0,ymax), ylab="Counts")
    
    ### grid
    par(xpd=F)
    grid()
    
    ### line
    list_percentile = c()
    list_colors = rev(rainbow(nrow(subdat)))
    for (i in 1:nrow(subdat)){
      abline(v=subdat_resistance[i], col=list_colors[i], lwd=2)
      list_percentile = c(list_percentile, sum(resistance>=subdat_resistance[i])/length(resistance))
    }
    
    ### legends
    par(xpd=F)
    legend("topright", title="The herbicide resistance situation of your farm in ", legend=paste0(subdat$Location[!is.na(subdat_resistance)], "(", subdat$Accession_Name[!is.na(subdat_resistance)], ") is lower (better) than other ", round(list_percentile[!is.na(subdat_resistance)]*100), "% farms"), col=list_colors[!is.na(subdat_resistance)], pch=c(19,19), box.col = F, cex=.9)
  }
  dev.off()
}
```