---
title: "Herbicide Resistance Level of your farm"
---
```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

### Histograms of the herbicide resistance level
The following plots show herbicide resistance of "Clethodim", "Glyphosate", "Sulfometuron", and "Terbuthylazine".
You can see your situation (highlighted lines) compared to other neighbour farms
```{r, Histograms}
par(mfrow=c(2,2), xpd=TRUE, mar=c(4,4,4,4))
for (name_herbicide in list_herbicides){
  # name_herbicide = list_herbicides[3]
  resistance = eval(parse(text=paste0("dat$", name_herbicide)))
  resistance = resistance[!is.na(resistance)]
  subdat_resistance = eval(parse(text=paste0("subdat$", name_herbicide)))
  if (sum(!is.na(subdat_resistance))==0){
    plot(x=0:1, y=0:1, type="n", xlab=name_herbicide, ylab="")
    text(x=0.5, y=0.5, lab="NO DATA")
  } else {
    hist(resistance, col=rgb(0.5,0.5,0.5,alpha=0.6), breaks=10, bord=FALSE, main="", xlim = c(0,1), xlab=name_herbicide, ylim = c(0,10), ylab="Frequency")
    par(xpd=F)
    grid()
    list_percentile = c()
    list_colors = rev(rainbow(nrow(subdat)))
    for (i in 1:nrow(subdat)){
      abline(v=subdat_resistance[i], col=list_colors[i], lwd=2)
      list_percentile = c(list_percentile, sum(resistance>=subdat_resistance[i])/length(resistance))
    }
    par(xpd=T)
    legend(x=-0.15, y=14, title="The herbicide resistance situation of your farm in ", legend=paste0(subdat$Location[!is.na(subdat_resistance)], " is lower (better) than other ", round(list_percentile[!is.na(subdat_resistance)]*100), "% farms"), col=list_colors[!is.na(subdat_resistance)], pch=c(19,19), box.col = F, cex=.9)
  }
}
```

### Heatmap of the herbicide resistance level
#### You can see your situation in a bigger view
```{r, Maps}
library(maps)
orig_par = par(no.readonly=TRUE)
for (herbicide in c("Clethodim", "Glyphosate", "Sulfometuron", "Terbuthylazine")){
  # herbicide = "Glyphosate"
  
  if (sum(!is.na(eval(parse(text=paste0("subdat$", herbicide, "_SURVIVAL_RATE"))))) == 0 ){
    next
  }
  
  landscape_gradient = readRDS(paste0("./data/landscape_surfaces_gradient_data_", herbicide, ".rds"))
  predx = landscape_gradient$predx
  predy = landscape_gradient$predy
  Z = landscape_gradient$Z
  
  ncolors = 25 ### 25 is a nice number to see dicrete contour lines across the landscape methinks...
  color_gradient = rev(colorRampPalette(c("#A50026","#D73027","#F46D43","#FDAE61","#FEE08B","#FFFFBF","#D9EF8B","#A6D96A","#66BD63","#1A9850","#006837"))(ncolors))
  
  par(orig_par)
  layout(matrix(c(rep(1,5),2),nrow=1))
  ### define x-y limits
  dx=c(min(predx), max(predx))
  dy=c(min(predy), max(predy))
  xaxis = seq(round(min(predx)), round(max(predx)), 2)
  yaxis = seq(round(min(predy))-2, round(max(predy))+2, 2)
  ### prepare the box enclosing the map
  plot(0, xlim=dx, ylim=dy, asp=1, type="n", xlab="Longitude", ylab="Latitdue", main=paste0(herbicide, " Resistance Gradient"), xaxt="n", yaxt="n") #empty
  ### overlay the heatmap
  par(new=TRUE)
  image(x=predx, y=predy, z=Z, col=color_gradient[round(min(Z)*ncolors):round(max(Z)*ncolors)], xlab="", ylab="", main="", asp=1, xaxt="n", yaxt="n")
  ### extract the bounding box of the map
  outline = maps::map("world", plot=FALSE)
  xrange = range(outline$x, na.rm=TRUE)
  yrange = range(outline$y, na.rm=TRUE)
  xbox = xrange + c(-2, 2)
  ybox = yrange + c(-2, 2)
  ### draw the outline of the map and color the water blue
  polypath(c(outline$x, NA, c(xbox, rev(xbox))),
         c(outline$y, NA, rep(ybox, each=2)),
         col="light blue", rule="evenodd")
  ### name the ticks with degree signs ("\U00B0")
  axis(side=1, at=xaxis, labels=paste0(xaxis, "\U00B0"))
  axis(side=2, at=yaxis, labels=paste0(yaxis, "\U00B0"),las=2)
  ### add a grid 'cause it looks noice
  grid(col="darkgray")
  ### plot points
  par(new=TRUE)
  plot(0, xlim=dx, ylim=dy, asp=1, type="n", xlab="", ylab="", main="", xaxt="n", yaxt="n") #empty
  # plot(0, xlim=dx, ylim=dy, asp=1, type="n", xlab="", ylab="", main="")
  for (i in 1:nrow(subdat)){
    x = subdat$Coordinates_E[i]
    y = subdat$Coordinates_N[i]
    r = eval(parse(text=paste0("subdat$", herbicide, "_SURVIVAL_RATE")))[i]
    if (!is.na(r)){
      points(x, y, col="black", bg=color_gradient[round(r*ncolors)+1], pch=19)
      text(x, y, lab=subdat$Location[i], pos=1)
    }
  }
  ### plot heat map legend
  legend_x=seq(from=0,to=1, length=length(color_gradient))
  legend_y=seq(from=0, to=1, length=length(color_gradient))
  legend_z = matrix(rep(legend_x, times=length(color_gradient)), byrow=TRUE, nrow=length(color_gradient))
  plot(x=c(0,1), y=c(0,1), type="n", xlab="", ylab="", xaxt="n", yaxt="n", main="")
  par(new=TRUE)
  image(x=legend_x, y=legend_y, z=legend_z, col=color_gradient, xlab="", ylab="", main="", xaxt="n", las=2)
  mtext("Completely\nResistant", side=3, line=0.5, at=0.5, cex=0.5)
  mtext("Completely\nSusceptible", side=1, line=1.5, at=0.5, cex=0.5)
}
```