---
title: "Your personal report of herbicide resistance"
output: html_document
---

```{r, setup, include=F}
knitr::opts_chunk$set(echo = F)
# # -------------------------------------------------------
# # test-used, close this area when running iteration,
# library(tidyverse)
# library(png)
# library(grid)
# getwd()
# # -------------------------------------------------------
```

```{r, load-title, include=F}
# # --------------test-used data---------------------------------
# # close this area when running iteration,
# # because title_pngs are only needed to be loaded once
# 
# title_png_1 <- readPNG("../img/title/Clethodim.png")
# title_png_2 <- readPNG("../img/title/Glyphosate.png")
# title_png_3 <- readPNG("../img/title/Sulfometuron.png")
# title_png_4 <- readPNG("../img/title/Terbuthylazine.png")
# 
# # list_title_png = list()
# # for (t in 1:length(title_name_vec)) {
# #   title_png <- readPNG(paste0("../img/title/", title_name_vec[t]))
# #   list_title_png[t] = title_png
# # } # store image in a list is complex; failed
# 
# # plot.new()
# # grid.raster(title_png_2, x = unit(0.25, "npc"), y = unit(0.4, "npc"),  width = 1, height = 0.1)
# # -----------------------------------------------------------
```

```{r, display}
# # ---------------test area--------------------------------
# df = read.csv("../data/combined_dataframe.csv", header=TRUE, na.strings=c("#N/A", "-"))
# 
# list_farmers_path = list.files("../img")
# 
# list_Herbicides = c("Clethodim", "Glyphosate", "Sulfometuron", "Terbuthylazine")
# 
# df_commercial_name_of_herbicide <- read.csv(file = '../data/Commercial name of herbicides.csv', header=TRUE)
# 
# farmer = "Kim Lyons (c/o Andrew Speirs)"
# 
# # --- close when running iteration--------------------------

# sub data frame of each farmer
sub_df = df[df$Farmer_Agronomist == farmer, ]

for (herbcide in list_Herbicides) {
  # herbcide = "Clethodim"
  
  ## load image img1 is hist; img2 is map
  # ### ---------------remove slash------------------------
  # farmers_path_name = gsub("/", " ", farmer)
  # ### -----------close when running iteration------------
  
  img1 <- readPNG(paste0("../img/", farmers_path_name, "/", "hist_",  herbcide, ".png"))
  img2 <- readPNG(paste0("../img/", farmers_path_name, "/", "map_",  herbcide, ".png"))
  
  par(mar=(rep(0,4)))
  plot.new()
  
  ## display title image
  if (herbcide=="Clethodim") {
    rasterImage(title_png_1, 0, 0.85, 1, 1)
  }
  if (herbcide=="Glyphosate") {
    rasterImage(title_png_2, 0, 0.85, 1, 1)
  }
  if (herbcide=="Sulfometuron") {
    rasterImage(title_png_3, 0, 0.85, 1, 1)
  }
  if (herbcide=="Terbuthylazine") {
    rasterImage(title_png_4, 0, 0.85, 1, 1)
  }
  
  ## display hist and map images
  rasterImage(img1, 0, 0, 0.5, 0.85)
  rasterImage(img2, 0.5, 0, 1, 0.85)
  ### failed
  # grid.raster(img1, x = unit(0.25, "npc"), y = unit(0.4, "npc"),  width = 0.5)
  # grid.raster(img2, x = unit(0.75, "npc"), y = unit(0.4, "npc"), width = 0.5)
  
  
  ## display text of sample size
  ### Commercial name
  commercial_name = df_commercial_name_of_herbicide$Product.Name[which(df_commercial_name_of_herbicide$Active.Ingredient..a.i.. == herbcide)] # "Status Clethodim"
  
   print(paste0("The sample size in ", herbcide, " (", commercial_name, ") ", "resistance test of"))
  
  list_acc_no = sub_df$Accession_Name[]
  for (acc_no in list_acc_no) {
    # acc_no = "ACC03"
    toEval = paste0("sub_df$", herbcide, "_sampleSize", "[sub_df$Accession_Name[]==", "'", acc_no, "'", "]")
    
    samplSize = eval(parse(text = toEval))
    
    print(paste0(acc_no, ": ", samplSize))
  }
}

```


