---
title: "Herbicide Resistance Report"
date: 19 Oct 2020
output: html_document
---

```{r, setup, include=F}
knitr::opts_chunk$set(echo = F)
# -------------------------------------------------------
# test-used, close this area when running iteration,
library(tidyverse)
library(png)
library(grid)

getwd()
# ------------close when running iteration----------------
```

```{r, test-only, include=F}
# -------------------------------------------------------
farmer = "Kim Lyons (c/o Andrew Speirs)"
df = read.csv("../data/combined_dataframe.csv", header=TRUE, na.strings=c("#N/A", "-"))

list_farmers_path = list.files("../img")

list_Herbicides = c("Clethodim", "Glyphosate", "Sulfometuron", "Terbuthylazine")

df_commercial_name_of_herbicide <- read.csv(file = '../data/Commercial name of herbicides.csv', header=TRUE)
# -----------close when running iteration--------------------
```


```{css, echo=FALSE}
h2 {
  text-align: left;
  font-size: 20pt;
}

h3 {
  text-align: center;
  font-size: 24pt;
}

.legend {
  width: 300px;
  height: 380px;
  border-radius: 8px;
  padding: 1.2em 0.7em 1.2em 0.4em;
  box-sizing: border-box;
  position: relative;
  top: 60px;
  right: 0;
  background: #EBF5FB
}
```

```{r}
# sub data frame of each farmer
sub_df = df[df$Farmer_Agronomist == farmer, ]
```

<!-- Outer -->
## Dear `r farmer` {.tabset}

```{r, display, results='asis'}
color_bg = c("#FDEDEC", "#E8DAEF", "#D6EAF8", "#D5F5E3")
color_text = c("#7B241C", "#5B2C6F", "#154360", "#145A32")
for (i in 1:length(list_Herbicides)) {
  # list_Herbicides[1] = "Clethodim"
  
  # Commercial name
  commercial_name = df_commercial_name_of_herbicide$Product.Name[which(df_commercial_name_of_herbicide$Active.Ingredient..a.i.. == list_Herbicides[i])] ## "Status Clethodim"
  
  # tabName
  cat('\n\n### ', list_Herbicides[i], '\n\n')
  
  cat('\n\n',
    '<div align="center">',
      '<p style="font-size:17px">', 
        '<span style="color:#21618C;font-weight:bold;font-size: 120%">', commercial_name,
        '</span>',
      ' (Commercial name)', 
      '</p>',
    '</div>',
    '\n\n')
  
  # plots
  ## load image img1 is hist; img2 is map
  ### ---------------remove slash------------------------
  farmers_path_name = gsub("/", " ", farmer)
  ### -----------close when running iteration------------
  
  img1 <- readPNG(paste0("../img/", farmers_path_name, "/", "hist_",  list_Herbicides[i], ".png")) # histogram
  img2 <- readPNG(paste0("../img/", farmers_path_name, "/", "map_",  list_Herbicides[i], ".png")) # map
  
  ## div outer
  cat('\n\n:::: {style="display: flex;"} \n\n')
  ## div inner 1
  cat('\n\n::: {} \n\n')
  
  par(mar=(rep(0,4)))
  plot.new()
  rasterImage(img1, 0, 0, 0.5, 1)
  rasterImage(img2, 0.5, 0, 1, 1)
  
  cat('\n\n::: \n\n')
  
  ## div inner 2, display text of sample size and place of each ACC
  cat('\n\n::: {.legend} \n\n')

  list_acc_no = sub_df$Accession_Name[]
  for (acc_no in list_acc_no) {
    # acc_no = "ACC42"
    
    toEval = paste0("sub_df$", list_Herbicides[i], "_sampleSize", "[sub_df$Accession_Name[]==", "'", acc_no, "'", "]")
    samplSize = eval(parse(text = toEval))
    
    if (samplSize != "NA") {
      cat("\n\n", '* ',
        "The sample size of ",
        '`', acc_no, '`', "in",
        '`', df$Location[df$Accession_Name==acc_no], '`',
        "is",
        '`', samplSize, '`',
        "\n\n")
    }

  }
  
  note = c("Clethodim is an acetyl-CoA carboxylase (ACCase) inhibitor, which disrupts fatty acid biosynthesis. [Post-emergent]",
     "Glyphosate is a 5-enolpyruvylshikimate-3-phosphate synthase (EPSPS) inhibitor, which disrupts the synthesis of aromatic amino acids - tyrosine, tryptophan and phenylalanine [Post-emergent]",
     "Sulfometuron is an acetolactate synthase (ALS) or acetohydroxy acid synthase (AHAS) inhibitor, which disrupts the synthesis of branched amino acids - valine, leucine and isoleucine. [Pre- and post-emergent]",
     "Terbuthylazine is a photosystem II (PSII) inhibitor. [Post-emergent]")
    cat("\n\n",
      '<p style="text-align:justify;margin-left:20px;margin-right: 15px;color:#AEB6BF">',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '</p>',
      "\n\n")
    
  cat("\n\n",
      '<p style="text-align:justify;margin-left:28px;margin-right: 17px">',
      note[i],
      '</p>',
      "\n\n")
      
  cat('\n\n::: \n\n')
  
  cat('\n\n:::: \n\n')
  

  cat('\n\n:::: {} \n\n')
  cat('\n\n', '\n\n')
  cat('\n\n:::: \n\n')
  
}

```

## {-} 




